# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# Ghost Reference Index
ghostRefIndex=D:/GitHub/MarkusBordihn/Ghost-Reference-Index/gradle/ghost-ref-minecraft-1.21.1.gradle
# Project
version=12.1.0
group=de.markusbordihn.adaptiveperformancetweaks
vendor_name=markusbordihn
# Mod
mod_id=adaptive_performance_tweaks
mod_name=Adaptive Performance Tweaks
mod_author=Markus Bordihn
mod_namespace=adaptiveperformancetweaks
# Common
minecraft_version=1.21.1
# Forge Mod Loader
forge_version=52.0.28
# Forge Helper Mods
forge_spark_mod=4738952
forge_xaeros_minimap_mod=5862251
# NeoForge Mod Loader
neoforge_version=21.1.229
# NeoForge Helper Mods
neoforge_spark_mod=
neoforge_xaeros_minimap_mod=5862252
# Fabric Mod Loader
fabric_version=0.107.0+1.21.1
fabric_loader_version=0.16.9
fabric_loom=1.9-SNAPSHOT
# Fabric Helper Mods
fabric_spark_mod=4738953
fabric_xaeros_minimap_mod=5862253
# Publish to CurseForge
curseforge_release_type=alpha
curseforge_project_id=450269
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=alpha
modrinth_project_id=kLawTYXp
modrinth_api_token=Never put your token here!
