# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[0,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "MIT"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId = "adaptive_performance_tweaks"
version = "${file.jarVersion}"
displayName = "APTweaks (Bundle)"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks/"
displayTest = "IGNORE_SERVER_VERSION"
logoFile = "logo.png"
credits = ""
authors = "Markus Bordihn"
description = '''Adaptive Performance Tweaks (Bundle) is a collection of Minecraft Forge Mods to automatically adjust specific settings on the server side to allow a better tps/fps.'''

[[dependencies.adaptive_performance_tweaks]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adaptive_performance_tweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adaptive_performance_tweaks]]
modId = "adaptive_performance_tweaks_core"
mandatory = true
versionRange = "[11.0.0,12.0.0)"
ordering = "NONE"
side = "SERVER"

[[dependencies.adaptive_performance_tweaks]]
modId = "adaptive_performance_tweaks_gamerules"
mandatory = true
versionRange = "[11.0.0,12.0.0)"
ordering = "NONE"
side = "SERVER"

[[dependencies.adaptive_performance_tweaks]]
modId = "adaptive_performance_tweaks_items"
mandatory = true
versionRange = "[11.0.0,12.0.0)"
ordering = "NONE"
side = "SERVER"

[[dependencies.adaptive_performance_tweaks]]
modId = "adaptive_performance_tweaks_player"
mandatory = true
versionRange = "[11.0.0,12.0.0)"
ordering = "NONE"
side = "SERVER"

[[dependencies.adaptive_performance_tweaks]]
modId = "adaptive_performance_tweaks_spawn"
mandatory = true
versionRange = "[11.0.0,12.0.0)"
ordering = "NONE"
side = "SERVER"
