# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  core:
    needs: setup
    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./core
    - name: Build core with Gradle
      run: ./gradlew build
      working-directory: ./core

  bundle:
    needs: setup
    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./bundle
    - name: Build bundle with Gradle
      run: ./gradlew build
      working-directory: ./bundle

  gamerules:
    needs: setup
    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./gamerules
    - name: Build gamerules with Gradle
      run: ./gradlew build
      working-directory: ./gamerules

  items:
    needs: setup
    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./items
    - name: Build items with Gradle
      run: ./gradlew build
      working-directory: ./items
